# fly.toml app configuration file generated for cold-wave-6497 on 2023-06-24T15:42:21+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cold-wave-6497"
primary_region = "waw"

[build]
  image = "gromozeka1/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dk9vbibn3"
  CloudinarySettings__ApiKey="717925642367712"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
